@echo off
REM ****************************************************************************
REM Vivado (TM) v2017.4.1 (64-bit)
REM
REM Filename    : compile.bat
REM Simulator   : Xilinx Vivado Simulator
REM Description : Script for compiling the simulation design source files
REM
<<<<<<< HEAD
REM Generated by Vivado on Sun Mar 18 22:14:08 -0700 2018
REM SW Build 2117270 on Tue Jan 30 15:32:00 MST 2018
=======
REM Generated by Vivado on Sun Mar 18 22:15:28 -0700 2018
REM SW Build 2086221 on Fri Dec 15 20:55:39 MST 2017
>>>>>>> f12426c5cf62ff1d2aeb313ea42e2c8009021e19
REM
REM Copyright 1986-2017 Xilinx, Inc. All Rights Reserved.
REM
REM usage: compile.bat
REM
REM ****************************************************************************
echo "xvlog --incr --relax -prj tb_para_mult_vlog.prj"
call xvlog  --incr --relax -prj tb_para_mult_vlog.prj -log xvlog.log
call type xvlog.log > compile.log
if "%errorlevel%"=="1" goto END
if "%errorlevel%"=="0" goto SUCCESS
:END
exit 1
:SUCCESS
exit 0
